#!/bin/bash

#requirements:
#bash
#user created with sudo privs and script be in their home
#internet connection
#GRAPHICS DRIVERS

#VARIABLES
USER="ray"
GITUSER="raygarner"
EMAIL="ray@perfectcast.co.uk"
EMAIL2="psyrg4@nottingham.ac.uk"

#update 
read -rp "updating system..."
sudo pacman -Syu

#cd to home dir
read -rp "Moving to /home/$USER"
cd "/home/$USER" || exit

#create dirs
read -rp "Creating dirs in new user home..."
mkdir media media/audio media/audio/music media/pics media/pics/papes media/pics/screenshots media/vids media/vids/shows media/vids/films media/vids/screencasts Documents builds Downloads .config .config/zsh src Downloads/music Downloads/isos/ Downloads/vids games

#create zsh history
touch "/home/$USER/.config/zsh/history"

#install packages
read -rp "Installing packages..."
cd "/home/$USER/" || exit
sudo pacman -S --needed zathura zathura-pdf-mupdf make gvim gnu-free-fonts xorg xorg-xinit redshift mpv scrot htop sudo vi pulseaudio compton acpi git xorg-xsetroot xorg-server dmenu libx11 freetype2 pkg-config transmission-cli base-devel neofetch xclip openssh unzip perl-rename pulsemixer gdb gimp unrar texlive-most texlive-lang pandoc dosfstools nano alsa-utils bluez bluez-utils pulseaudio-bluetooth pulseaudio-alsa pass zip cups gutenprint sxiv xorg-xrandr numlockx zsh git-lfs biber imagemagick dash glew sdl2 sdl2_image glm python-pip speedtest-cli mutt lynx calcurse fakeroot newsboat webkit2gtk gcr gst-plugins-good gst-libav mediainfo p7zip dolphin-emu pdftk

#ghc ghc-static cabal-install stack haskell-haddock-library alex happy musescore virtualbox octave dolphin-emu pro-audio wine

#set keyboard layout
read -rp "Setting keyboard layout to gb..."
sudo localectl --no-convert set-x11-keymap gb

#set up git
read -rp "Adding git account details..."
git config --global user.email "$EMAIL"
git config --global user.name "$GITUSER"
cd "/home/$USER" || exit

#set up pass
gpg --full-generate-key
pass init "$EMAIL"
pass insert "$EMAIL"
pass insert "$EMAIL2"

#download dotfiles
read -rp "Downloading dotfiles..."
git clone https://github.com/raygarner/dotfiles.git dotfiles

#download newsboat config
read -rp "Downloading newsboat config..."
git clone https://github.com/raygarner/newsboat-config.git .newsboat

#download mutt config
read -rp "Downloading mutt config..."
git clone https://github.com/raygarner/mutt-config.git .mutt 

#download calcurse config
read -rp "Downloading calcurse config..."
rm -r .calcurse
git clone https://github.com/raygarner/calcurse-config.git .calcurse

#download vis config
read -rp "Downloading vis config..."
cd .config
git clone https://github.com/raygarner/vis-config.git vis

#link dotfiles to home
read -rp "Linking dotfiles..."
cd "/home/$USER/dotfiles" || exit
ln .vimrc "/home/$USER/.vimrc"
ln .xbindkeysrc "/home/$USER/.xbindkeysrc"
ln .xinitrc "/home/$USER/.xinitrc"
ln .zshrc "/home/$USER/.zshrc"
ln .aliases "/home/$USER/.aliases"
ln .zprofile "/home/$USER/.zprofile"
ln .urlview "/home/$USER/.urlview"
cd "/home/$USER" || exit

#download uni.bib
cd /home/$USER/Documents
git clone https://github.com/raygarner/latex.git
cd /home/$USER

#set shell
chsh -s /bin/zsh

#download scripts
read -rp "Downloading scripts..."
git clone https://github.com/raygarner/scripts.git
chmod +x scripts/*

#download and build dwm
read -rp "Downloading dwm..."
cd builds || exit
git clone https://github.com/raygarner/rays_dwm.git
read -rp "Building dwm..."
cd rays_dwm || exit
make
sudo make install
cd "/home/$USER/builds" || exit

#download and build st
read -rp "Downloading st..."
git clone https://github.com/raygarner/rays_st_3.git
read -rp "Building st..."
cd rays_st_3 || exit
make
sudo make install
cd "/home/$USER/builds" || exit

#download and build surf
read -rp "Downloading surf..."
git clone https://github.com/raygarner/rays_surf_2.git
read -rp "Building surf..."
cd rays_surf_2 || exit
make
sudo make install
cd "/home/$USER/builds" || exit

#download and build slock
read -rp "Downloading slock..."
git clone https://github.com/raygarner/rays_slock.git
read -rp "Building slock..."
cd rays_slock || exit
make
sudo make install
cd "/home/$USER/builds" || exit

#download and build farbfeld
read -rp "Downloading farbeld..."
git clone https://git.suckless.org/farbfeld
read -rp "Building farbfeld..."
cd farbfeld || exit
make
sudo make install
cd "/home/$USER/builds" || exit

#download and build sent
read -rp "Downloading sent..."
git clone https://github.com/raygarner/rays_sent.git
read -rp "Building sent..."
cd rays_sent || exit
make
sudo make install
cd "/home/$USER/builds" || exit

#download and build yay
read -rp "Downloading yay..."
git clone https://aur.archlinux.org/yay.git
read -rp "Building yay..."
cd yay || exit
makepkg -si
cd "/home/$USER/builds" || exit

#install visualizer
#read -rp "Install cli-visualizer"
#yay -S cli-visualizer

#install urlview
read -rp "Installing urlview..."
yay -S urlview

#install xbindkeys
read -rp "Installing xbindkeys..."
yay -S xbindkeys

#install scid
#read -rp "Installing scid..."
#yay -S scid

#install stockfish
#read -rp "Installing stockfish..."
#yay -S stockfish

#install brave
read -rp "Installing brave..."
yay -S brave-bin

#install mons
read -rp "Installing mons..."
yay -S mons

#install xwallpaper
read -rp "Installing xwallpaper..."
yay -S xwallpaper

#install reaper
read -rp "installing reaper..."
yay -S reaper-bin

#install youtube-dl
read -rp "installing youtube-dl..."
sudo pip install youtube-dl

#install eclipse
#read -rp "installing eclipse-java..."
#yay -S eclipse-java

#install tremc
read -rp "installing tremc..."
yay -S tremc

#install teams
#read -rp "installing teams..."
#yay -S teams

#install trello
#read -rp "installing trello..."
#yay -S trello

#install slack
#read -rp "installing slack..."
#yay -S slack-desktop

#install android-studio
#read -rp "installing android studio..."
#yay -S android-studio

#installing matlab ncurses dependancy
#read -rp "Installing ncurses5-compat-libs (for matlab)..."
#yay -S ncurses5-compat-libs

#install matlab
#read -rp "Installing matlab..."
#yay -S matlab

#download and build citrix
#server: citrix.nottingham.ac.uk
#read -rp "Downloading icaclient..."
#git clone https://aur.archlinux.org/icaclient.git
#read -rp "Building icaclient..."
#cd icaclient || exit
#makepkg -si
#mkdir -p "/home/$USER/.ICAClient/cache"
#cp /opt/Citrix/ICAClient/config/{All_Regions,Trust_Region,Unkown_Region,canonicalization,regions}.ini "/home/$USER/.ICAClient"
#cd "/home/$USER/builds" || exit
#read -rp "Adding SSL support to icaclient..."
#sudo ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts/
#sudo c_rehash /opt/Citrix/ICAClient/keystore/cacerts/
#read -rp "Creating /bin shortcut for icaclient..."
#cd /bin
#echo '#!/bin/sh' | sudo tee -a icaclient
#echo '/opt/Citrix/ICAClient/selfservice' | sudo tee -a icaclient
#sudo chmod +x icaclient
#cd "/home/$USER/builds" || exit

#download and build vmware-horizon
#server: nottingham.cloud
#read -rp "Downloading vmware-keymaps..."
#git clone https://aur.archlinux.org/vmware-keymaps.git
#read -rp "Building vmware-keymaps..."
#cd vmware-keymaps || exit
#makepkg -si
#cd "/home/$USER/builds" || exit
#read -rp "Downloading vmware-horizon-client..."
#git clone https://aur.archlinux.org/vmware-horizon-client.git
#read -rp "Building vmware-horizon-client..."
#cd vmware-horizon-client || exit
#makepkg -si
#cd "/home/$USER" || exit

#enable the wifi device with netctl
INTERFACE=$(ip link | grep ^3 | awk '{print $2}' | cut -b '1-6')
sudo systemctl enable netctl-ifplugd@$INTERFACE.service
sudo systemctl enable netctl-auto@$INTERFACE.service

#start and enable dhcpcd
read -rp "Starting dhcpcd module..."
sudo systemctl enable dhcpcd.service

#start and enable bluetooth service
read -rp "Enabling bluetooth.service..."
sudo systemctl enable bluetooth.service

#start and enable cups
read -rp "Enabling cups service..."
sudo systemctl enable org.cups.cupsd.service

#enable transmission
read -rp "Enabling transmission service..."
sudo systemctl enable transmission.service

#bluetooth conf stuff
read -rp "Configuring pulseaudio for bluetooth compatability..." 
echo '' | sudo tee -a /etc/pulse/system.pa
echo 'load-module module-bluetooth-policy' | sudo tee -a /etc/pulse/system.pa
echo 'load-module module-bluetooth-discover' | sudo tee -a /etc/pulse/system.pa

#relink /bin/sh
read -rp "Relinking /bin/sh to dash..."
sudo ln -sfT dash /usr/bin/sh

#downloading hosts
sudo cp /etc/hosts /etc/hosts.d
curl "https://someonewhocares.org/hosts/zero/hosts" | sudo tee -a /etc/hosts
curl "https://adaway.org/hosts.txt" | sudo tee -a /etc/hosts
curl "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext" | sudo tee -a /etc/hosts

echo 'End of script.'
echo 'You should now reboot.'
